export const DefaultReportArray = {
	Performance_Summary_Total: {
		customizable: false,
		reportIds: [1, 8],
		inReport: true,
		sortBy: "reportType",
		limit: 3,
		headers: [
			{
				value: "timeStamp",
				format: "string",
				label: "Compared Dates",
				comp: false,
				addClass: "",
			},
			{
				value: "Sales",
				format: "dollar",
				label: "Sales",
				comp: true,
				addClass: "",
			},
			{
				value: "Click Throughs",
				format: "string",
				label: "Clicks",
				comp: true,
				addClass: "",
			},
			{
				value: "# of Sales",
				format: "int",
				label: "# of Sales",
				comp: true,
				addClass: "",
			},
			{
				value: "Avg Order Amount",
				format: "string",
				label: "Avg Order Amount",
				comp: true,
				addClass: "",
			},
			{
				value: "Conversion Rate",
				format: "string",
				label: "Conversion Rate",
				comp: true,
				addClass: "",
			},
			{
				value: "New Customer %",
				format: "string",
				label: "New Customer %",
				comp: true,
				addClass: "",
			},
			{
				value: "Mobile Sales",
				format: "string",
				label: "Mobile Sales",
				comp: true,
				addClass: "",
			},
		],
	},

	Product_Sold_List: {
		customizable: false,
		reportIds: 18,
		inReport: true,
		sortBy: "Total Product Sale Quantity",
		joinKey: "Product Name",
		headers: {
			"Product Name": { yoy: false, dataType: "string" },
			"Product SKU": { yoy: false, dataType: "string" },
			"Sale Count ": { yoy: true, dataType: "currency" },
			"Total Product Sale Amount": { yoy: true, dataType: "currency" },
		},
	},
	Performance_Summary_By_Day_Graph: {
		id: 12,
		inReport: true,
		headers: {
			"CPC Earnings": { yoy: true, dataType: "currency" },
			"Network CPC Earnings": { yoy: true, dataType: "currency" },
			Date: false,
			"Ad Impressions": { yoy: true, dataType: "int" },
			"Click Throughs": { yoy: true, dataType: "int", display: true },
			Sales: { yoy: true, dataType: "currency" },
			"# of Sales": { yoy: true, dataType: "int", display: true },
			"# of Mobile Sales": { yoy: true, dataType: "int", display: true },
			"Mobile Sales": { yoy: true, dataType: "currency" },
			"# of Adjustments": { yoy: true, dataType: "int", display: true },
			"New Customers": { yoy: true, dataType: "int", display: false },
			"New Customer Sales": { yoy: true, dataType: "currency" },
			Commissions: { yoy: true, dataType: "currency" },
			Incentives: { yoy: true, dataType: "currency", display: true },
			"Network Commissions": { yoy: true, dataType: "currency" },
			"Conversion Rate": { yoy: false, dataType: "percent" },
			"Average Sale Amount": { yoy: true, dataType: "currency" },
			"New Customer %": { yoy: true, dataType: "percent" },
			"Click Through Rate": { yoy: true, dataType: "percent" },
			Merchant: { yoy: false, dataType: "string" },
			Weekday: { yoy: false, dataType: "string", display: true },
		},
	},
	Product_Performance_By_Departments_and_Brands: {
		customizable: false,
		reportIds: 18,
		inReport: true,
		sortBy: "Total Product Sale Quantity",
		joinKey: "Product Name",
		headers: {
			"Brand Name": { yoy: false, dataType: "string" },
			Category: { yoy: false, dataType: "string" },
			Department: { yoy: false, dataType: "string" },
			Merchant: { yoy: false, dataType: "string" },
			"Product Name": { yoy: false, dataType: "string" },
			"Product SKU": { yoy: false, dataType: "string" },
			"Sale Count ": { yoy: true, dataType: "currency" },
			"Sub Category": { yoy: false, dataType: "string" },
			"Total Product Sale Amount": { yoy: true, dataType: "currency" },
			"Total Product Sale Quantity": { yoy: true, dataType: "int" },
		},
	},
	Performance_Summary_By_Affiliate: {
		id: 20,
		inReport: true,
		sortBy: "Sales",
		joinKey: "Affiliate Id",
		headers: {
			"Affiliate Id": { yoy: false, dataType: "string" },
			"Website Category": { yoy: false, dataType: "string" },
			"Ad Impressions": { yoy: true, dataType: "int", display: true },
			"Click Throughs": { yoy: true, dataType: "int", display: true },
			Sales: { yoy: true, dataType: "currency" },
			"# of Sales": { yoy: true, dataType: "int", display: true },
			"# of Mobile Sales": { yoy: true, dataType: "int", display: true },
			"Mobile Sales": { yoy: true, dataType: "currency" },
			"# of Adjustments": { yoy: true, dataType: "int", display: true },
			"New Customers": { yoy: true, dataType: "int", display: false },
			"New Customer Sales": { yoy: true, dataType: "currency" },
			Commissions: { yoy: true, dataType: "currency" },
			Incentives: { yoy: true, dataType: "currency" },
			"Network Commissions": { yoy: true, dataType: "currency" },
			"Conversion Rate": { yoy: false, dataType: "percent" },
			"Average Sale Amount": { yoy: true, dataType: "currency" },
			"New Customer %": { yoy: true, dataType: "percent" },
			"Click Through Rate": { yoy: true, dataType: "percent" },
			"Affiliate Tags": { yoy: false, dataType: "string" },
		},
	},
	Performance_Summary_By_Affiliate_Website: {
		id: 20,
		inReport: true,
		sortBy: "Sales",
		joinKey: "Website Id",
		headers: {
			"Website Id": { yoy: false, dataType: "string" },
			"Affiliate Id": { yoy: false, dataType: "string" },
			"Affiliate Website Name": { yoy: false, dataType: "string" },
			"Affiliate Website": { yoy: false, dataType: "string" },
			"Website Category": { yoy: false, dataType: "string" },
			"Affiliate Category": { yoy: false, dataType: "string" },
			"Ad Impressions": { yoy: true, dataType: "int", display: true },
			"Click Throughs": { yoy: true, dataType: "int", display: true },
			Sales: { yoy: true, dataType: "currency" },
			"# of Sales": { yoy: true, dataType: "int", display: true },
			"# of Mobile Sales": { yoy: true, dataType: "int", display: true },
			"Mobile Sales": { yoy: true, dataType: "currency" },
			"# of Adjustments": { yoy: true, dataType: "int", display: true },
			"New Customers": { yoy: true, dataType: "int", display: false },
			"New Customer Sales": { yoy: true, dataType: "currency" },
			Commissions: { yoy: true, dataType: "currency" },
			Incentives: { yoy: true, dataType: "currency" },
			"Network Commissions": { yoy: true, dataType: "currency" },
			"Conversion Rate": { yoy: false, dataType: "percent" },
			"Average Sale Amount": { yoy: true, dataType: "currency" },
			"New Customer %": { yoy: true, dataType: "percent" },
			"Click Through Rate": { yoy: true, dataType: "percent" },
		},
	},
	Performance_Summary_By_Sub_Affiliate_Website: {
		id: 20,
		inReport: true,
		sortBy: "Sales",
		joinKey: "Website Id",
		headers: {
			"CPC Earnings": { yoy: true, dataType: "currency" },
			"Network CPC Earnings": { yoy: true, dataType: "currency" },
			"Placement Earnings": { yoy: true, dataType: "currency" },
			"Network Placement Earnings": { yoy: true, dataType: "currency" },
			"Website Id": { yoy: false, dataType: "string" },
			"Affiliate Id": { yoy: false, dataType: "string" },
			"Affiliate Website Name": { yoy: false, dataType: "string" },
			"Affiliate Website": { yoy: false, dataType: "string" },
			"Website Category": { yoy: false, dataType: "string" },
			"Affiliate Category": { yoy: false, dataType: "string" },
			"Ad Impressions": { yoy: true, dataType: "int", display: true },
			"Click Throughs": { yoy: true, dataType: "int", display: true },
			Sales: { yoy: true, dataType: "currency" },
			"# of Sales": { yoy: true, dataType: "int", display: true },
			"# of Mobile Sales": { yoy: true, dataType: "int", display: true },
			"Mobile Sales": { yoy: true, dataType: "currency" },
			"# of Adjustments": { yoy: true, dataType: "int", display: true },
			"New Customers": { yoy: true, dataType: "int", display: false },
			"New Customer Sales": { yoy: true, dataType: "currency" },
			Commissions: { yoy: true, dataType: "currency" },
			Incentives: { yoy: true, dataType: "currency" },
			"Network Commissions": { yoy: true, dataType: "currency" },
			"Conversion Rate": { yoy: false, dataType: "percent" },
			"Average Sale Amount": { yoy: true, dataType: "currency" },
			"New Customer %": { yoy: true, dataType: "percent" },
			"Click Through Rate": { yoy: true, dataType: "percent" },
			"Affiliate Tags": { yoy: false, dataType: "string" },
		},
	},
	Custom_Performance_Summary_Array: {
		id: 20,
		inReport: true,
		sortBy: "Sales",
		joinKey: "Website Id",
		headers: [
			{
				value: "Affiliate Name",
				format: "string",
				label: "Affiliate Name",
				comp: false,
				addClass: "",
			},
			{
				value: "Click Throughs",
				format: "int",
				label: "Click Throughs",
				comp: true,
				addClass: "small-cell",
			},
			{
				value: "# of Sales",
				format: "int",
				label: "# of Sales",
				comp: true,
				addClass: "small-cell",
			},
			{
				value: "Sales",
				format: "dollar",
				label: "Sales",
				comp: true,
				addClass: "small-cell",
			},
			{
				value: "Commissions",
				format: "dollar",
				label: "Commissions",
				comp: true,
				addClass: "small-cell",
			},
			{
				value: "Conversion Rate",
				format: "percent",
				label: "Conversion Rate",
				comp: true,
				addClass: "small-cell",
			},
			{
				value: "AOV",
				format: "dollar",
				label: "AOV",
				comp: true,
				addClass: "small-cell",
			},
		],
	},
};
