export const getSettings = () => {
	try {
		const raw = localStorage.getItem("ChettiToolsSettings");
		return raw ? JSON.parse(raw) : {};
	} catch {
		return {};
	}
};

export const _adminApiModules = {
	// REMOVED REPORT ELEMENTS >>Add as neccessary
	// Performance_Summary_By_Week: { id: 50, inReport: false },
	// Calendar_Period_Trending: { id: 63, inReport: false },
	// Calendar_Period_Trending_By_Affiliate: { id: 65, inReport: false },
	// Calendar_Period_Trending_By_Affiliate_Website: {
	// 	id: 66,
	// 	inReport: false,
	// },
	// Rolling_Period_Trending: { id: 67, inReport: false },
	// Rolling_Period_Trending_By_Affiliate: { id: 69, inReport: false },
	// Rolling_Period_Trending_By_Affiliate_Website: {
	// 	id: 70,
	// 	inReport: false,
	// },
	// Affiliate_Application_Approvals: { id: 85, inReport: false },
	// Ad_Impressions_Summary: { id: 2, inReport: false },
	// Ad_Impressions_Detail: { id: 3, inReport: false },
	// Click_Throughs_Summary: { id: 5, inReport: false },
	// Click_Throughs_Detail: { id: 6, inReport: false },
	// Referral_Domain_By_Affiliate: { id: 79, inReport: false },
	// Last_Click_Through_to_Sale_Summary: { id: 72, inReport: false },
	// First_Click_Through_to_Sale_Summary: { id: 83, inReport: false },
	// Sales_Commissions_Detail: { id: 8, inReport: false },
	// Sale_Hit_Tracking_Trails: { id: 19, inReport: false },
	// Datafeed_Download_Summary: { id: 16, inReport: false },
	// Invalid_Affiliate_Links: { id: 23, inReport: false },
	// Performance_Summary_By_Discount: { id: 100, inReport: false },
	// Performance_Summary_By_Ad_Tool: { id: 9, inReport: false },
	Performance_Summary: {
		id: 1,
		inReport: true,
		sortBy: "Sales",
		headers: {
			"Merchant Id": false,
			Merchant: false,
			"Ad Impression": true,
			"Click Through": true,
			Sales: true,
			Commissions: true,
			"Incentives ": true,
			"Network Commissions": true,
			"# of Sale": true,
			"# of Adjustment": true,
			"# of Mobile Sale": true,
			"Mobile Sales": false,
			"New Customer": false,
			"New Customer Sales": false,
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Placement Earnings": false,
			"Network Placement Earnings": false,
			"Conversion Rate": false,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
		},
	},
	Performance_Summary_By_Ad_Campaign: {
		id: 24,
		inReport: false,
		sortBy: "Sales",
		mergeby: "Ad Campaign/Subscription",
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Merchant Id": false,
			Merchant: false,
			"Ad Id": false,
			"Ad Campaign/Subscription": false,
			"Ad Type": false,
			"Ad Impressions": false,
			"Click Throughs": false,
			Sales: false,
			"# of Sales": false,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": false,
			"Conversion Rate": false,
			"New Customer %": false,
			"Click Through Rate": false,
		},
	},

	Performance_Summary_By_Affiliate: {
		id: 15,
		inReport: true,
		sortBy: "Sales",
		mergeBy: "Affiliate Id",
		staticDisplay: ["Affiliate", "Affiliate Id"],
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Placement Earnings": false,
			"Network Placement Earnings": false,
			"Affiliate Id": true,
			"Affiliate Name": false,
			Affiliate: true,
			"Ad Impressions": true,
			"Click Throughs": true,
			Sales: true,
			"# of Sales": true,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": true,
			"Conversion Rate": true,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
			Merchant: false,
			"Affiliate Tags": false,
		},
	},

	Performance_Summary_By_Affiliate_Website: {
		id: 20,
		inReport: true,
		sortBy: "Sales",
		mergeBy: "Website Id",
		staticDisplay: ["Affiliate Website Name"],
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Placement Earnings": false,
			"Network Placement Earnings": false,
			"Website Id": true,
			"Affiliate Id": true,
			"Affiliate Website Name": true,
			"Affiliate Website": false,
			"Website Category": false,
			"Affiliate Category": false,
			"Ad Impressions": true,
			"Click Throughs": true,
			Sales: true,
			"# of Sales": true,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": true,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: true,
			Incentives: true,
			"Network Commissions": false,
			"Conversion Rate": true,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
			"Affiliate Tags": false,
		},
	},

	Performance_Summary_By_Day: {
		id: 12,
		inReport: false,
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			Date: false,
			"Ad Impressions": false,
			"Click Throughs": false,
			Sales: false,
			"# of Sales": false,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": false,
			"Conversion Rate": false,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
			Merchant: false,
			Weekday: false,
		},
	},
	Performance_Summary_By_Hour: {
		id: 29,
		inReport: false,
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Time of Day": false,
			"Ad Impressions": false,
			"Click Throughs": false,
			Sales: false,
			"# of Sales": false,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": false,
			"Conversion Rate": false,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
			Merchant: false,
		},
	},
	Performance_Summary_By_Month: {
		id: 48,
		inReport: false,
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			Month: false,

			"Ad Impressions": false,
			"Click Throughs": false,
			Sales: false,
			"# of Sales": false,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": false,
			"Conversion Rate": false,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
			Merchant: false,
			Weekday: false,
		},
	},
	Performance_Summary_By_Product_Ad_Tools: {
		id: 31,
		inReport: false,
		sortBy: "Sales",
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Merchant Id": false,
			Merchant: false,
			"Product Name": false,
			"Product SKU": false,
			"Ad Impressions": false,
			"Click Throughs": false,
			Sales: false,
			"# of Sales": false,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: false,
			Incentives: false,
			"Network Commissions": false,
			"Conversion Rate": false,
			"Average Sale Amount": false,
			"New Customer %": false,
			"Click Through Rate": false,
		},
	},
	Performance_Summary_By_Sub_Affiliate_Partners: {
		id: 96,
		inReport: true,
		sortBy: "Sales",
		mergeBy: "Sub Affiliate Domain",
		staticDisplay: ["Sub Affiliate Domain", "Affiliate Name"],
		headers: {
			"CPC Earnings": false,
			"Network CPC Earnings": false,
			"Affiliate Id": false,
			"Sub Affiliate Domain": true,
			"Affiliate Name": true,
			Affiliate: true,
			"Click Throughs": true,
			Sales: true,
			"Gross Sales": true,
			"# of Sales": true,
			"# of Mobile Sales": false,
			"Mobile Sales": false,
			"# of Adjustments": false,
			"New Customers": false,
			"New Customer Sales": false,
			Commissions: true,
			Incentives: true,
			"Network Commissions": true,
			"Conversion Rate": true,
			"Average Sale Amount": true,
			"New Customer %": false,
			"Click Through Rate": false,
			Merchant: false,
			"Affiliate Tags": false,
		},
	},

	Product_Sold: {
		id: 18,
		inReport: true,
		sortBy: "Total Product Sale Quantity",
		mergeBy: "ProductName",
		staticDisplay: ["ProductName"],
		headers: {
			"Brand Name": true,
			Category: true,
			Department: true,
			Merchant: true,
			"Mobile Sale Count ": true,
			"Product Name": true,
			"Product SKU": true,
			"Sale Count ": true,
			Store: true,
			"Sub Category": true,
			"Total Product Sale Amount": true,
			"Total Product Sale Quantity": true,
		},
	},
	Outlet_Summary: {
		id: 90,
		inReport: true,
		sortBy: "Store Name",
		headers: {
			"Store Name": true,
			"# Sales": true,
			Qty: true,
			Mobile: true,
			Returns: true,
			Revenue: true,
			"Affiliate Commission": true,
			"Network Commission": true,
			"Total Commission": true,
		},
	},
	Performance_Summary_By_Custom_Tracking_Code: {
		id: 22,
		inReport: false,
	},
	Performance_Summary_by_Affiliate_Tag_Group: { id: 25, inReport: false },
};
